### ISSUE TITLE
invalid input syntax for type uuid: "undefined" Error

### ISSUE THREAD

**Issue by orangeleaf777** [AntonioErdeljac/next13-spotify#14]
Hi, I don't know how to solve this error. When I run npm run dev, I always get the 
**invalid input syntax for type uuid: "undefined"** Error
Can anyone give me some suggestion on how to solve this?
Thanks in advance.

**Comment by MurusMe** [comment]
This happened to me,

My issue was resolved once I rechecked my Supabase API keys. 

Turns out my `SUPABASE_SERVICE_ROLE_KEY` had been updated and changed. 

Hope this helps.

**Comment by orangeleaf777** [comment]
@MurusMe Hi, thanks a lot for your suggestion. However, I have checked my Supabase API keys and it still won't work. I still get the invalid input syntax for type uuid: "undefined" Error

**Comment by joaoricardoM** [comment]
Hi, did you find a solution to the problem? I'm having the same error and I can't detect it

**Comment by Mts79** [comment]
Hi, I'm having the same issue: invalid input syntax for type uuid: "undefined"
Nothing seems to work.

**Comment by AkashSaraf-16** [comment]
@orangeleaf777, @joaoricardoM, @Mts79 please check for the typos. In my case I was using the wrong command, the ### **correct** one is:
`stripe listen --forward-to localhost:3000/api/webhooks`
Similarly you guys also check for typos in naming the folder related to stripe i.e., app/api/webhooks/route.ts and files under **lib** folder. Hope this will solve your issue.

**Comment by littleblackone** [comment]
the reason is this line:  const userSongs = await getSongsByUserId(); in app/layout.tsx.
when the user has not logged in, this method still use the user_Id to get user's songs, so you only need to add a  logic to get songs when the user exists.
const { data } = await supabase.auth.getUser();
if (data.user) {
    userSongs = await getSongsByUserId();
  }
 you can pass userSongs like this: songs={userSongs ?? []}
